fix(ReconnectLDAPObject): reconnect race condition
There is a race condition in ReconnectLDAPObject._apply_method_s() when
multiple threads use a shared ReconnectLDAPObject instance:

> Traceback (most recent call last):
...
>   File "ldap/ldapobject.py", line 1259, in search_ext_s
>     return self._apply_method_s(SimpleLDAPObject.search_ext_s,*args,**kwargs)
>   File "ldap/ldapobject.py", line 1201, in _apply_method_s
>     self.reconnect(self._uri,retry_max=self._retry_max,retry_delay=self._retry_delay)
>   File "ldap/ldapobject.py", line 1181, in reconnect
>     SimpleLDAPObject.unbind_s(self)
>   File "ldap/ldapobject.py", line 905, in unbind_s
>     return self.unbind_ext_s(None,None)
>   File "ldap/ldapobject.py", line 889, in unbind_ext_s
>     msgid = self.unbind_ext(serverctrls,clientctrls)
>   File "ldap/ldapobject.py", line 881, in unbind_ext
>     res = self._ldap_call(self._l.unbind_ext,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
>   File "ldap/ldapobject.py", line 352, in __getattr__
>     self.__class__.__name__,repr(name)
> AttributeError: ReconnectLDAPObject has no attribute '_l'

While the reconnect() is already protected by `self._reconnect_lock`,
there is a small windows between the `unbind_s()` and `reconnect()`
call, where CPython can switch threads: While the 1st threads is already
waiting inside `reconnect()` for its next try, the 2nd threads will call
`unbind_s()` outside that lock which will race with the 1st thread also
calling `unbind_s()`: Whoever comes first will do the `del self._l`
first, so the later threads will raise the above AttributeError.

Move calling `unbind_s()` inside the locked region so that `self._l` is
handled atomically.

Add a new parameter `force` to either forcefully close any previous
connection or keep re-use the previous connection if it still is
supposed to work.