Fix filter string error
When executed with Python 3 the replace throw the error:

TypeError: a bytes-like object is required, not 'str'

Converting to sting fix the problem.